# convert JSON 2 CSV once a day

name: Convert JSON to CSV data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '03 23 * * *'
    #- cron:  '* * 29 2 *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: move empty API response / Error Messages to separate Folder
      run: wc *.json -l | grep " 8 " | rev | cut -f2 -d " " | rev | xargs mv -t error_messages_from_API_call
    - name: Convert latest vbb & TIER data
      run: |-
        query_date=$(date +"%y%m%d")
        service=vbb
        #touch CSV_per_day/${query_date}${service}.csv
        jq '.[] | [ .tripId, .when, .stop.location.latitude, .stop.location.longitude ] | @csv' JSON_source/${query_date}*${service}*.json > CSV_per_day/${query_date}${service}.csv
        service=TIER
        #touch CSV_per_day/${query_date}${service}.csv
        jq '.data[] | [ .attributes.lastLocationUpdate, .attributes.vehicleType, .attributes.lat, .attributes.lng  ] | @csv' JSON_source/${query_date}*${service}*.json > CSV_per_day/${query_date}${service}.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
