# convert JSON 2 CSV once a day

name: Convert JSON to CSV data

on:
  #push:
  workflow_dispatch:
  schedule:
    - cron:  '03 0 * * *'
    #- cron:  '* * 29 2 *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: move empty API response / Error Messages to separate Folder
      run: |-
        nfiles=$(wc JSON/*.json -l | grep " 8 " | wc -l)
        echo "number of empty Files: $nfiles"
        if (($nfiles > 0)); then
        wc JSON/*.json -l | grep " 8 " | rev | cut -f1 -d " " | rev | xargs mv -t JSON/error_messages_from_API_call
        fi
        echo "total number of Files: $(ls JSON/*.json | wc -l)"
    - name: Convert latest vbb & TIER data
      run: |-
        query_date=$(date +%y%m%d -d "Yesterday")
        service=vbb
        echo ID, created_at, vehicle, latitude, longitude > CSV/${query_date}${service}.csv
        jq -r '.[] | [ .tripId, .when, .line.name, .stop.location.latitude, .stop.location.longitude ] | @csv' JSON/${query_date}*${service}*.json >> CSV/${query_date}${service}.csv
        service=TIER
        echo ID, created_at, vehicle, latitude, longitude > CSV/${query_date}${service}.csv
        jq -r '.data[] | [ .id, .attributes.lastLocationUpdate, .attributes.vehicleType, .attributes.lat, .attributes.lng  ] | @csv' JSON/${query_date}*${service}*.json >> CSV/${query_date}${service}.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
