# convert JSON 2 CSV once a day

name: Convert JSON to CSV data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '03 23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Convert latest data
      run: |-
        #jq -r '.[] \
        #| map(.tripId), map(.when), map(.stop.location.latitude), map(.stop.location.longitude) \
        #| @csv' JSON_source/$(date +"%y%m%d")*_vbb_arrivals.json \
        #| awk '{for(i=1;i<=NF;i++)a[i][NR]=$i}END{for(i in a)for(j in a[i])printf"%s"(j==NR?"\n":FS),a[i][j]}' FS=,\
        #>> CSV_per_day/$(date +"%y%m%d")_VBB.csv
        #json2csv -i JSON_source/$(date +"%y%m%d")*_TIER*.json >> CSV_per_day/$(date +"%y%m%d")_TIER.csv
        #json2csv -i JSON_source/$(date +"%y%m%d")*_vbb*.json >> CSV_per_day/$(date +"%y%m%d")_VBB.csv
        ###
        jq .[]."tripId" JSON_source/$(date +"%y%m%d")*_vbb_arrivals.json | awk '{for(i=1;i<=NF;i++)a[i][NR]=$i}END{for(i in a)for(j in a[i])printf"%s"(j==NR?"\n":FS),a[i][j]}' FS=, >> CSV_per_day/_$(date +"%y%m%d")_VBB.csv
        jq .[]."when" JSON_source/$(date +"%y%m%d")*_vbb_arrivals.json | awk '{for(i=1;i<=NF;i++)a[i][NR]=$i}END{for(i in a)for(j in a[i])printf"%s"(j==NR?"\n":FS),a[i][j]}' FS=, >> CSV_per_day/_$(date +"%y%m%d")_VBB.csv
        awk '{for(i=1;i<=NF;i++)a[i][NR]=$i}END{for(i in a)for(j in a[i])printf"%s"(j==NR?"\n":FS),a[i][j]}' FS=, CSV_per_day/_$(date +"%y%m%d")_VBB.csv > CSV_per_day/$(date +"%y%m%d")_VBB.csv
        rm _$(date +"%y%m%d")_VBB.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
