# convert JSON 2 CSV once a day

name: Convert JSON to CSV data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '03 23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Convert latest data
      run: |-
        cat $(date +"%y%m%d")*_TIER*.json | json2csv >> ../CSV_per_day/$(date +"%y%m%d")_TIER.csv
        cat $(date +"%y%m%d")*_vbb*.json | json2csv >> ../CSV_per_day/$(date +"%y%m%d")_VBB.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
