# convert JSON 2 CSV once a day

name: Convert JSON to CSV data

on:
  push:
  workflow_dispatch:
  schedule:
    #- cron:  '03 23 * * *'
    - cron:  '* * 29 2 *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Convert latest vbb (& TIER) data
      run: |-
        #jq '.[]|[.tripId,.when,.stop.location.latitude,.stop.location.longitude]|@csv' JSON_source/$(date +"%y%m%d")*vbb*.json  >> CSV_per_day/_$(date +"%y%m%d")_VBB.csv
        #rm CSV_per_day/_*.csv
        ###
        touch  CSV_per_day/_.csv
        query_date=$(bash date -d "Today -5 days" +"%y%m%d")
        service=vbb
        jq '.[] | [ .tripId, .when, .stop.location.latitude, .stop.location.longitude ] | @csv' JSON_source/$query_date*$service*.json  >> CSV_per_day/$query_date$service.csv
        service=TIER
        jq '.data[] | [ .attributes.lastLocationUpdate, .attributes.vehicleType, .attributes.lat, .attributes.lng  ] | @csv' JSON_source/$query_date*$service*.json  >> CSV_per_day/$query_date$service.csv
        rm CSV_per_day/_*.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
