# convert JSON 2 CSV once a day

name: Convert JSON to CSV data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '03 23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Convert latest data
      run: |-
        wget https://github.com/jehiah/json2csv/releases/download/v1.2.1/json2csv-1.2.1.linux-amd64.go1.13.5.tar.gz
        tar -xzf json2csv-1.2.1.linux-amd64.go1.13.5.tar.gz
        rm json2csv-1.2.1.linux-amd64.go1.13.5.tar.gz
        mv json2csv-1.2.1.linux-amd64.go1.13.5/json2csv .
        rmdir json2csv-1.2.1.linux-amd64.go1.13.5
        chmod 777 json2csv
        json2csv -i JSON_source/$(date +"%y%m%d")*_TIER*.json >> CSV_per_day/$(date +"%y%m%d")_TIER.csv
        json2csv -i JSON_source/$(date +"%y%m%d")*_vbb*.json >> CSV_per_day/$(date +"%y%m%d")_VBB.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
