name: Scrape VBB & TIER data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '32 6,7,8,9,15,16,17,18 * * *'
    #- cron:  '* * 29 2 *' # basically never runs!

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl 'https://v5.bvg.transport.rest/stops/900000160004/arrivals?duration=10&linesOfStops=false&remarks=true&language=en' \
        -H 'accept: application/json' \
        | jq . > JSON_source/$(date +"%y%m%d%H")_vbb_arrivals.json
        curl -X 'GET' "https://platform.tier-services.io/v1/vehicle?lat=52.509434&lng=13.497544&radius=200" \
        -H 'X-Api-Key: bpEUTJEBTf74oGRWxaIcW7aeZMzDDODe1yBoSxi2' -H 'accept: application/json' \
        | jq . > JSON_source/$(date +"%y%m%d%H")_TIER_availability.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
